---
title: 作用域
date: 2019-09-11 22:05:15
tags:
categories:
- 前端
- 作用域与闭包
---

```javascript
var a = 2;
/**
1、 遇到 var a , 编译器会询问作用域是否已经有一个该名称的变量存在于同一个作用域的集合中。如果是，编译器会忽略该声明，继续进行编译；否则它会要求作用域在当前作用域的集合中声明一个新的变量，并命名为 a。
2、接下来编译器会为引擎生成运行时所需的代码，这些代码被用来处理 a = 2 这个赋值操作。引擎运行时会先询问作用域，在当前的作用域集合中是否存在一个叫作 a 的变量。如果是，引擎就会使用这个变量；如果否，引擎会继续查找该变量。

如果引擎最终找到了 a 变量，就会将 2 赋值给它。否则引擎就会举手示意并抛出一个异常！
**/
```

**总结：**变量的赋值操作会执行两个动作

1、编译器会在当前作用域中声明（如果之前没有声明过）；

2、在运行时引擎会在作用域中查找该变量，如果找到就会对它赋值。

作用域是一套规则，用于确定在何处以及如何查找变量（标识符）。

***如果查找的目的是对变量进行赋值，那么就会使用 LHS 查询；***

***如果查找的目的是获取变量的值，就会使用RHS查询。***

赋值操作赋会导致 LHS 查询。 = 操作赋或调用函数时传人的参数都会导致关联作用域的赋值操作。

不成功的 RHS 引用会导致抛出 ReferenceError 异常。不成功的 LHS 引用会导致自动隐式 地创建一个全局变量(非严格模式下)，该变量使用 LHS 引用的目标作为标识符，或者抛 出 ReferenceError 异常(严格模式下)。

```javascript
console.log(c);
// => ReferenceError: c is not defined ; 不成功的 RHS 
b = 1;  
// => 不成功 LHS创建了一个全局变量
function hello () {
  'use strict';
   b = 1;
}
hello();
//  ReferenceError: b is not defined; 严格模式下， LHS 失败抛出异常
```

**小测验**

```javascript
function foo (a) {
  var b = a;
  return a + b;
}
var c = foo(2);

// 1. 找出所有的 LHS 查询（这里有 3 处！）
// c = ..; a = 2(传参隐式分配); b = ..;
// 2. 找出所有的 RHS 查询（这里有 4 处！）
// foo(2) 中的 foo ; b = a 中的 a ; a + b 中的 a 和 b
```



函数作用域与块级作用域的行为是一样的，可以总结为： **任何声明在某个作用域内的变量，都将附属于这个作用域**

```javascript
a = 2;
var a;
console.log(a);
// => a

// 包括变量和函数在内的所有声明都会在任何代码被执行前首先被处理。
```

函数声明和变量声明都会被提升。但是一个值得注意的细节(这个细节可以出现在有多个“重复”声明的代码中)是函数会首先被提升，然后才是变量。

```javascript
foo(); // 1
var foo;
function foo() { console.log( 1 );
}
foo = function() { console.log( 2 );
};
// 这个代码片段会被引擎理解为如下形式
function foo() { console.log( 1 );
}
foo(); // 1
foo = function() { console.log( 2 );
};
```

